#!/bin/bash
export LIBRARY_PATH=${LIBRARY_PATH}:${HOME}/lib
#To actually use shared library set
#export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/lib
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:${PWD}/../../src
pip install -e .
